import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:eventhub/models/ticket_type.dart';
import 'package:eventhub/repositories/event_repository.dart';
import 'package:go_router/go_router.dart';

class TicketTiersScreen extends ConsumerStatefulWidget {
  final String eventId;
  const TicketTiersScreen({super.key, required this.eventId});

  @override
  ConsumerState<TicketTiersScreen> createState() => _TicketTiersScreenState();
}

class _TicketTiersScreenState extends ConsumerState<TicketTiersScreen> {
  Future<void> _showAddTicketDialog() async {
    final nameController = TextEditingController();
    final priceController = TextEditingController();
    final quantityController = TextEditingController();
    DateTime? salesStart = DateTime.now();
    DateTime? salesEnd = DateTime.now().add(const Duration(days: 30));

    await showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Add Ticket Tier'),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextField(
                  controller: nameController,
                  decoration: const InputDecoration(labelText: 'Tier Name (e.g. VIP)'),
                ),
                TextField(
                  controller: priceController,
                  decoration: const InputDecoration(labelText: 'Price'),
                  keyboardType: TextInputType.number,
                ),
                TextField(
                  controller: quantityController,
                  decoration: const InputDecoration(labelText: 'Total Quantity'),
                  keyboardType: TextInputType.number,
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => context.pop(),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () async {
                final price = double.tryParse(priceController.text) ?? 0;
                final qty = int.tryParse(quantityController.text) ?? 0;
                if (nameController.text.isEmpty || qty <= 0) return;

                final newTicket = TicketType(
                  id: '', // Generated by DB
                  eventId: widget.eventId,
                  name: nameController.text,
                  price: price,
                  quantityTotal: qty,
                  salesStart: salesStart!,
                  salesEnd: salesEnd!,
                );

                try {
                  await ref.read(eventRepositoryProvider).createTicketType(newTicket);
                  if (context.mounted) {
                    context.pop();
                    setState(() {}); // Refresh list
                  }
                } catch (e) {
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
                  }
                }
              },
              child: const Text('Save'),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Manage Ticket Tiers')),
      body: FutureBuilder<List<TicketType>>(
        future: ref.read(eventRepositoryProvider).getTicketTypes(widget.eventId),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          }

          final tickets = snapshot.data ?? [];
          if (tickets.isEmpty) {
            return const Center(child: Text('No ticket tiers created yet.'));
          }

          return ListView.builder(
            itemCount: tickets.length,
            itemBuilder: (context, index) {
              final t = tickets[index];
              return ListTile(
                title: Text(t.name),
                subtitle: Text('Sold: ${t.quantitySold} / ${t.quantityTotal}'),
                trailing: Text('\$${t.price.toStringAsFixed(2)}'),
              );
            },
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showAddTicketDialog,
        child: const Icon(Icons.add),
      ),
    );
  }
}
